### PR TITLE
Make metrics port configurable

### LINKED ISSUE #515: metrics port hardcoded to 8383 in tigera-operator conflicting with CNV
## Expected Behavior

Metrics port in tigera-operator should be configurable, and default value should be different than 8383 which is used by nmstate-handler pods from CNV (Container Native Virtualization in RedHat Openshift 4.x. Instead it is hardcoded to 8383 here: https://github.com/tigera/operator/blob/master/pkg/daemon/daemon.go#L35
 

## Current Behavior

Currently it is not possible to properly deploy CNV (Container Native Virtualization) on RedHat Openshift 4.x with Calico and tigera-operator. Both tigera-operator and one of nmstate-handler pods (part of CNC) run with host network and try to bind to port 8383. Since tigera-operator is deployed first, nmstate-handler keeps crashing and CNV deployment cannot finish properly.

## Possible Solution

1. make metrics port configurable, and
2. change default port 8383 to something else

## Steps to Reproduce (for bugs)

1. deploy RedHat Openshift 4.3.12 with Calico as specified in RedHat documentation and the following page: https://docs.projectcalico.org/getting-started/openshift/installation
2. deploy CNV according to RedHat documentation: https://docs.openshift.com/container-platform/4.3/cnv/cnv_install/installing-container-native-virtualization.html
3. list pods in openshift-cnv namespace and look for crashing nmstate-handler running on the same node as tigera-operator
4. scale down tigera-operator to 0 replicas to stop tigera-operator pod
5. restart failed nmstate-handler pod - it should be able to run successfully
6. inspect status of hco/kubevirt-hyperconverged in openshift-cnv namespace - the last status condition should state "Reconcile completed successfully"

## Your Environment

* Operating System and version: Redhat OpenShift 4.3.12 with Calico deployed using tigera-operator v1.3.3
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by ozdanborne**
## Description

Fixes #515

Replaces #604 

Operator currently serves prometheus metrics on port 8383. This is not configurable. This is problematic because operator is run in hostNetworked mode, and will conflict with any other service running on port 8383 on the node. Several users have reported this happening due to a service in openshift that also uses 8383.

It seems like this code hasn't been touched since the original boiler plate was checked in during the initial commit. Given that, I've taken some liberties to adjust the default behavior from here on out.

This PR:
- Exposes host and port via the `METRICS_HOST` and `METRICS_PORT` environment variables. If both are empty strings, metrics will be shut off.
- Changes default port to 8484. This will be used if only `METRICS_HOST` is specified.

I did some validation testing:
- :heavy_check_mark: running without setting `METRICS_HOST` and `METRICS_PORT` (or setting them to a blank string) results in metrics not being run
- :heavy_check_mark: running with `METRICS_HOST=localhost` runs metrics on 8383
- :heavy_check_mark: running with `METRICS_PORT=8384` runs metrics on 8484

## For PR author

- [ ] Tests for change.
- [x] If changing pkg/apis/, run `make gen-files`
- [x] If changing versions, run `make gen-versions`

## For PR reviewers

A note for code reviewers - all pull requests must have the following:

- [x] Milestone set according to targeted release.
- [x] Appropriate labels:
  - `kind/bug` if this is a bugfix.
  - `kind/enhancement` if this is a a new feature.
  - `enterprise` if this PR applies to Calico Enterprise only.

### CODE REVIEW

File: pkg/daemon/daemon.go [hunk 1]
```diff
@@ -46,6 +43,13 @@ func Main() {
 		os.Exit(1)
 	}
 
+	metricsAddr := os.Getenv("METRICS_BIND_ADDRESS")
```
Comment (caseydavenport) [inline pkg/daemon/daemon.go:46]: You might want this to be two separate variables - METRICS_HOST and METRICS_PORT.

Main reason being that users can then use the Kubernetes downward API to set the HOST portion to the node's IP address based on where the pod lands, without needing to bind to all addresses.
